Fix issue #11 - handle promise error
ifactory-solutions/awesome-react-app pull request #14
Opened 2017-10-06 00:45 UTC by sethfork

Added a catch statement to handle the createApp promise error

2017-10-06 00:50 UTC, jvcjunior commented
Hey @sethfork great work! I`ll ask guys here to check your code and test! Thanks a lot!

2017-10-06 09:57 UTC, italopessoa requested changes

2017-10-06 09:57 UTC, italopessoa commented on awesomeCreateApp.js
> +    .catch(console.error)
with this approach the error object itself is being logged, the result will be

>{ ChildProcessError: `create-react-app f1` failed with code 1
    at ChildProcess.<anonymous> (C:\Users\italo\AppData\Roaming\npm\node_modules\awesome-react-app\node_modules\child-process-promise\lib\index.js:132:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\italo\AppData\Roaming\npm\node_modules\awesome-react-app\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  name: 'ChildProcessError',
  code: 1,
  childProcess:
   ChildProcess {
     domain: null,
     _events: { error: [Function: t], close: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _closesNeeded: 1,
     _closesGot: 1,
     connected: false,
     signalCode: null,
     exitCode: 1,
     killed: false,
     spawnfile: 'C:\\WINDOWS\\system32\\cmd.exe',
     _handle: null,
     spawnargs:
      [ 'C:\\WINDOWS\\system32\\cmd.exe',
        '/s',
        '/c',
        '"C:\\WINDOWS\\system32\\cmd.exe /s /c "create-react-app "f1"""' ],
     pid: 6948,
     stdin: null,
     stdout: null,
     stderr: null,
     stdio: [ null, null, null ],
     emit: [Function] },
  stdout: undefined,
  stderr: undefined }

try to add a cool message 😃 
I'll add more steps on the issue, so you can test by yourself

2017-10-09 20:17 UTC, jvcjunior commented
Hey @sethfork are you still going to work on this? If so, please can you create your PR from your master to ours and also test locally to see if it's working before submit the PR? I'll close this one because I'll delete develop branch. 

Thanks a lot!

2017-10-09 20:17 UTC, closed without merging