Add git init and precommit hook for eslint
ifactory-solutions/awesome-react-app pull request #47
Opened 2017-10-11 15:24 UTC by ceejtron

As per #43 this adds precommit hooks for eslint. In addition, this adds a new question for initializing a git repository since precommit hooks can't be automatically set up unless a git repository has already been initialized.

2017-10-11 15:41 UTC, italopessoa commented
Well done @ceejtron. Seems that is everything ok. Let's wait for the reviewers. Thank you for your contribution ❤️

2017-10-11 17:36 UTC, jouderianjr commented on hooks/eslint/index.js
> +  const eslintDependencies = [
Nice Refactor mate

2017-10-11 17:39 UTC, jouderianjr requested changes
Hey, nice work! I'm pretty happy to see a new hook 💃

2017-10-11 17:39 UTC, jouderianjr commented on hooks/git/index.js
> +  return spawn(command, [], terminalOpts)
So, We tried to find if has some issue on create-react-app related with that and I've found this PR https://github.com/facebookincubator/create-react-app/pull/1288

So, looks like that will be added at some moment, what do you think about test if already has a git started? maybe just test if exists .git folder.

2017-10-11 18:38 UTC, paulonotz0r commented
Nice, @ceejtron! This is really cool!

In addition, can you add `commit lint` too? You can use the same as used on ifactory-solutions/inside-client#8.

Thank you for the contribution.

2017-10-11 20:14 UTC, ceejtron commented
Added a check for .git as well as a commitlint hook

2017-10-13 11:26 UTC, paulonotz0r approved these changes
Great!

2017-10-13 13:47 UTC, jouderianjr requested changes
Just 2 minor things, then you will merge it! 💃

2017-10-13 13:47 UTC, jouderianjr commented on hooks/git/index.js
> +  else {
Could you please use else in the same line? 😄

2017-10-13 13:47 UTC, jouderianjr commented on hooks/commitlint/index.js
> +    .then(() => {
You can do that as one line 
` .then(() => loadPackageJsonFromPath(`${cwd}/${folderName}/package.json`))`

2017-10-13 16:13 UTC, ceejtron commented
@jouderianjr pushed the changes you asked for

2017-10-13 16:51 UTC, jouderianjr approved these changes

2017-10-13 16:52 UTC, merged

2017-10-13 16:52 UTC, jouderianjr commented
Awesome @ceejtron thanks for your work 💃