use of eslint
ifactory-solutions/awesome-react-app pull request #49
Opened 2017-10-14 13:40 UTC by mbeatrizmagalhaes

Fix #1 

I added eslint and am using de .eslintrc that was already in the project, since I believe is a style you agree on. If you want it other way, let me know.

2017-10-17 12:23 UTC, paulonotz0r requested changes
Hey, @mbeatrizmagalhaes! Thank you for your PR! 

I have some suggestions: 

1) `awesome-react-some` is a CLI which is built in nodejs. And you are using a React linter in the dev dependencies;

2) You are using the hook eslint config (which it will be added to the new app created by the CLI) as the project (awesome-react-app) eslint config in the test script. However, it needed to add an eslint config file to the project root (like is commonly used).

So, I think changing this you are ready to go.

2020-05-04 11:16 UTC, beatriz commented
Hi! I don't understand how I let this PR slip, I'm sorry! 😞  
Would it still be useful if I completed this or is the project no longer maintained?

2020-05-06 15:19 UTC, jvcjunior commented
Go ahead @beatriz ! You can create the PR, no problem. Thanks for your help

2020-05-07 13:54 UTC, beatriz commented
I've updated the linting dependencies, removed the react linter dependencies and added a specific `.eslintrc` config to the root.

2020-05-07 13:55 UTC, beatriz commented on package.json
> +    "test": "eslint . --no-eslintrc -c .eslintrc",
`--no-eslintrc` is necessary so that it doesn't try to use `./hooks/eslint/.eslintrc.json`.

2020-06-04 12:16 UTC, italopessoa approved these changes

2025-07-21 07:11 UTC, closed without merging